# Generated by Django 5.2.1 on 2025-05-18 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlacesVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('place_city', models.CharField(max_length=255)),
                ('place_zip', models.CharField(max_length=255)),
                ('visited_year', models.IntegerField()),
                ('visited_though', models.CharField(max_length=255)),
                ('place_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sourishtravellist.places')),
            ],
        ),
    ]
