# Generated by Django 5.2.1 on 2025-05-18 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourishtravellist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesvisited',
            name='record_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='placesvisited',
            name='record_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
